import type { Metadata } from 'next';
import { Lato, Open_Sans } from 'next/font/google';
import { Slide, ToastContainer } from 'react-toastify';
import 'react-toastify/ReactToastify.css';
import AuthProvider from './auth/AuthProvider';
import './globals.css';
import Navbar from './Navbar';
import QueryClientProvider from './QueryClientProvider';

export const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-opensans',
});

export const lato = Lato({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-lato',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${openSans.variable} ${lato.variable} m-0 p-0`}>
        <QueryClientProvider>
          <AuthProvider>
            <ToastContainer
              theme='light'
              closeOnClick
              draggable
              transition={Slide}
              autoClose={3000}
              limit={2}
            />
            <Navbar />
            <main className='container mx-auto py-5'>{children}</main>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
